trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
pr:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md 
    ################################ not doing a CI because the README.md isn't linked with the program

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "Pipeline started at $(date)"
  displayName: 'Start Time'

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run prettier:fix
  displayName: 'Format code with Prettier'

- script: |
    npm run lint:fix
  displayName: 'Lint code'

- script: |
    npm run test
  displayName: 'Run tests with coverage'

- script: |
    npm run build
  displayName: 'Build code'

- script: echo "Pipeline ended at $(date)"
  displayName: 'End Time'

- script: echo "PIPELINE SUCCESS WITHOUT ERRORS"
  displayName: 'Success Message'