trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "Pipeline started at $(date)"
  displayName: 'Start Time'

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run prettier
  displayName: 'Format code with Prettier'

- script: |
    npm run lint .
  displayName: 'Lint code'

- script: |
    npm run test
  displayName: 'Run tests with coverage'

- script: |
    npm run build
  displayName: 'Build code'

- script: echo "Pipeline ended at $(date)"
  displayName: 'End Time'

- script: echo "PIPELINE SUCCESS WITHOUT ERRORS"
  displayName: 'Success Message'