name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Start Time
      run: echo "Pipeline started at $(date)"

    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm install

    - name: Format code with Prettier
      run: npm run prettier:fix

    - name: Lint code
      run: npm run lint:fix

    - name: Run tests with coverage
      run: npm run test

    - name: Build code
      run: npm run build

    - name: End Time
      run: echo "Pipeline ended at $(date)"

    - name: Success Message
      run: echo "PIPELINE SUCCESS WITHOUT ERRORS"